### ISSUE TITLE
Core packages?

### ISSUE THREAD

**Issue by nfrerebeau** [benmarwick/ctv-archaeology#60] opened 2023-09-27 09:59 UTC
Only `rcarbon` is currently identified as a [core package](https://github.com/cran-task-views/ctv/blob/main/Documentation.md#main-text) in the CTV. Should we try to distinguish the most important packages? 

Given the diversity of applications, I'm not sure it would be possible/relevant to define such a selection (on what criteria?).

**Comment by SCSchmidt** [comment] 2023-09-27 18:35
Yes, I agree, I would struggle to define core packages. Maybe we just ignore it?

**Comment by benmarwick** [comment] 2023-09-29 16:20
I think it's worth to have some designated as core to help novices decide which package to start with when there are several that seem quite similar. From my perspective the criteria for identifying core packages is that they are very well documented, and there is evidence of extensive use in the community. So a novice will be well supported by documentation from the package authors, and they can easily find and study examples of other researchers using the package.

I believe this is the case with packages for dealing with C14 ages, there are several developed by archaeologists and others, but there is a good case for rcarbon to be a starting point for a novice because it is so well documented, and has been so widely used by archaeologists in many publications. I think those qualities make it unique among packages doing C14 calibration.

**Comment by nfrerebeau** [comment] 2023-10-02 09:32
Perhaps we can try to highlight one package per section based on these same qualities (documentation + usage)?

**Comment by benmarwick** [comment] 2023-10-14 22:28
That's a great idea, one package per section as core, yes! From my perspective rcarbon is pretty unique in terms of documentation quality and use indicated by citation. The tesselle packages are unique in the quality of documentation, and used in teaching (at least by me, perhaps others too?), they'd be good candidates for core also. 

Let's check in with the others, would you like to nominate a package per section as core, considering documentation and use? @scpederzani @SCSchmidt @lolosp @lsteinmann @LiYingWang @bbartholdy @joeroe

**Comment by joeroe** [comment] 2023-10-16 07:46
I agree that it would be helpful to highlight core packages, and/or to have some selection criteria in general. Is this supposed to be a comprehensive list, or more of a curated set of recommendations?

**Comment by SCSchmidt** [comment] 2023-10-16 08:39
The documentation says "The views are intended to have a sharp focus so that it is sufficiently clear which packages should be included (or excluded) - and they are not meant to endorse the "best" packages for a given task." -- if they are not meant to endorse "the best" package, I'd say they are supposed to be a comprehensive list.

**Comment by bbartholdy** [comment] 2023-10-19 19:47
It looks like other CTVs have only a handful of core packages, anywhere from 5-15, so one per section might be a bit much. Maybe we should focus on the sections specific to archaeology, since these will have more limited overlap than, e.g., Reproducible research. 

Based on previous proposals it seems like it is important to have clear selection criteria for the (core) packages, and these should not be subjective.

**Comment by benmarwick** [comment] 2023-10-19 20:28
Just to be sure we are all looking at the same thing, the draft CTV that we are discussing is here: https://github.com/benmarwick/ctv-archaeology/blob/master/Archaeology.md which is sharply focussed on packages that do things that are mostly distinct to archaeology or mostly used by archaeologists. This is the one we plan to submit to CRAN. 

The question would appreciate your input on is what packages among that list should be designated as core. So far we have rcarbon as a core package, which I think is deserving because it is uniquely well-documented, well-used, and frequently cited. Please let me know if you are aware of other packages by/for archaeologists that are similar to rcarbon in those respects. 

Our draft CTV list is distinct from the older, longer list of packages in the [readme](https://github.com/benmarwick/ctv-archaeology#readme) which I believe isn't suitable for an official CTV, according to the current guidelines, because it's too broad.

**Comment by benmarwick** [comment] 2024-08-12 23:44
Thanks so much @nfrerebeau, that is helpful. From my perspective the criteria for identifying core packages is that they are (a) very well documented, and there is (b) evidence of extensive use in the community. All those you mention are well-documented in my opinion. 

One way to measure 'extensive use' is to look for citations of a package in papers that do not include the author of the package. Of the ones you identified, I think rcarbon, leastcostpath, mortAAR, and zoolog qualify, since I'm aware of publications that cite those that are not authored by the package author. 

I believe kairos and tabula may be extensively used also, have you seen citations of them, or other documentation of use that would fit here? 

Thank you again for keeping this discussion productive!

**Comment by nfrerebeau** [comment] 2024-08-13 11:21
@benmarwick `tabula` is cited a little over a dozen times (this is not the case for `kairos`)... mainly in ecology, not archaeology :sweat_smile:

**Comment by nfrerebeau** [comment] 2024-08-13 11:21
Updated shortlist:

* Analysis of Dates and Chronological Patterns: `rcarbon`
* Quantitative Analysis: `tabula`
* Zooarchaeological Analysis: `zoolog`
* Mortuary Analysis: `mortAAR`
* Landscape Analysis: `leastcostpath`

**Comment by bbartholdy** [comment] 2024-08-15 20:38
Seems like it could be a lot of work to track down citations for these packages, not to mention studies using the packages without citing them. Maybe to incentivize the work it could be turned into a paper? Of course it would need slightly better framing than just 'what R-packages do archaeologists use?' (assuming such paper doesn't already exist). That way the work put into CTV can also have additional benefits.

**Comment by nfrerebeau** [comment] 2024-08-28 09:03
@bbartholdy I agree that tracking down citations isn't easy (I think I've read some thoughts on this on rOpenSci). Turning the CTV into a paper could also help publicize it to the community.

But for now, we need to take the first step. @benmarwick invited us almost a year ago to co-maintain this CTV, so maybe we can start the submission process to CRAN? I've gone through the documentation and it seems to me that we have all the elements. If the shortlist suits everyone to begin with, we can then include it in the CTV (it will always be possible to improve it in the future) and move forward?

**Comment by joeroe** [comment] 2024-08-28 14:12
> * Analysis of Dates and Chronological Patterns: `rcarbon`
> * Quantitative Analysis: `tabula`
> * Zooarchaeological Analysis: `zoolog`
> * Mortuary Analysis: `mortAAR`
> * Landscape Analysis: `leastcostpath`

I think this is a reasonable list to start with. The ecosystem of dedicated archaeology packages is still relatively underdeveloped (see @zackbatist and I's [recent paper on this](https://intarch.ac.uk/journal/issue67/13/index.html)), so we're simply not going to find lots of highly-cited packages. Even rcarbon—which I'm a big fan of and which all seem to agree is as 'core' as it gets—is far from the only good package for radiocarbon calibration, and in terms of citation count I'd bet it still loses out to Bchron. Given that, Ben's standard of "well documented and cited by someone other than the package author" sounds good. We will have to strike a balance between being descriptive and prescriptive.

Could we describe a more specific use for tabula than 'quantitative analysis', though? Diversity analysis? Frequency analysis?

**Comment by nfrerebeau** [comment] 2024-08-28 14:56
> Could we describe a more specific use for tabula than 'quantitative analysis', though? Diversity analysis? Frequency analysis?

The “Quantitative Analysis” section includes `tabula`, `skyscapeR` and `ISAAKiel/quantAAR`. We can move `skyscapeR` under “Landscape Analysis”. `tabula` and `ISAAKiel/quantAAR` can be moved to the “Artefact Analysis” section. Does this seem more consistent?

**Comment by joeroe** [comment] 2024-08-28 15:09
Oh sorry, I didn't realise the was just the section name. Though I agree that sounds like a more informative grouping.

**Comment by benmarwick** [comment] 2024-09-03 17:42
Thanks everyone, I think we've got a great list of core packages now. I've merged #70. Now onto CRAN submission!

**Closed by benmarwick** 2024-09-03 17:42 UTC
